### PR TITLE
EID-1060 Acceptance tests for eIDAS scheme unavailable error message

### PR DESCRIPTION
**Pull request by andrewchong**
Added scenarios:
  Scenario: English journey - User selects eIDAS scheme that is unavailable and receives correct error page
  Scenario: Welsh journey - User selects eIDAS scheme that is unavailable and receives correct error page

Added step definitions:
Given /a user starts the "(.*)" version of the eIDAS journey$/ do |language_version|
Then('they are presented with the correct eIDAS scheme unavailable error page') do

Modified step definition:
Given('they select eIDAS scheme {string}') do |scheme|

### CODE REVIEW

**Comment by jakubmiarka** [comment]
Isn't this being already tested by unit tests? https://github.com/alphagov/verify-frontend/blob/fde8ff072f4f78c460befe3b0d6b454fd71faeb8/spec/controllers/redirect_to_country_controller_spec.rb#L24

Does this "feature" require a full acceptance tests? Wouldn't unit/feature tests in fronted covered it?

**Comment by CharlesIC** [comment]
I think we do want to have an acceptance test that checks that we handle the no-response-from-country case, seems like good practice.

**Comment by jakubmiarka** [comment]
I'm not saying we shouldn't test it, I'm just questioning if acceptance tests are the right place for this test. If we're just testing whether a single page displays in English or Welsh based on a single condition (no-response-from-country) that this can easily be an unit/feature test. Also that's where the content for the pages lives, so updating the content will break these tests.

**Comment by CharlesIC** [comment]
We're gonna remove the English/Welsh test - you're right that belongs in the unit tests.
We're just gonna have a test to check we handle the no-response case correctly.

**Pull request merged**
